# Generated by Django 4.2.23 on 2025-09-03 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('validade_toxicologico', models.DateField(blank=True, null=True)),
                ('pis', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('filiacao_pai', models.CharField(blank=True, max_length=255, null=True)),
                ('filiacao_mae', models.CharField(blank=True, max_length=255, null=True)),
                ('cnh_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cnh_categoria', models.CharField(blank=True, max_length=5, null=True)),
                ('cnh_validade', models.DateField(blank=True, null=True)),
                ('dt_emissao_cnh', models.DateField(blank=True, null=True)),
                ('dt_primeira_cnh', models.DateField(blank=True, null=True)),
                ('numero_registro_cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista_criado_por', to=settings.AUTH_USER_MODEL)),
                ('responsavel_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista_responsavel', to=settings.AUTH_USER_MODEL)),
                ('usuario_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
