# Generated by Django 4.2.23 on 2025-09-07 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motoristas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('renavam', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('chassi', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('ano_modelo', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_combustivel', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo_criado_por', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, help_text='Motorista responsável pelo veículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='motoristas.motorista')),
            ],
        ),
    ]
